name: Publish to GitHub Packages

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@think41'
      
      - name: Change to client-js-standalone directory
        working-directory: ./client-js-standalone
        run: pwd
      
      - name: Install dependencies
        working-directory: ./client-js-standalone
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Build package
        working-directory: ./client-js-standalone
        run: npm run build
      
      - name: Publish to GitHub Packages
        working-directory: ./client-js-standalone
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
